name: CMake tests t8code with Clang compiler


#  This file is part of t8code.
#  t8code is a C library to manage a collection (a forest) of multiple
#  connected adaptive space-trees of general element types in parallel.
#
#  Copyright (C) 2025 the developers
#
#  t8code is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  t8code is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with t8code; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

env:
  DEBUG_CONFIG: "-O1"

on:
  workflow_call:
    inputs:
      MAKEFLAGS:
        required: true
        type: string
        description: 'Make flags to use for compilation (like -j4)'
      MPI:
        required: true
        type: string
        description: 'Use MPI for compilation (ON/OFF)'
      BUILD_TYPE:
        required: true
        type: string
        description: 'Build type (Release/Debug)'
      TEST_LEVEL:
        required: true
        type: string
        description: 'Test level used for configuring (T8_TEST_LEVEL_FULL, T8_TEST_LEVEL_MEDIUM, or T8_TEST_LEVEL_BASIC)'
        default: 'T8_TEST_LEVEL_FULL'

jobs:
  t8code_cmake_tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container: dlramr/t8code-ubuntu:t8-clang-dependencies
    steps:
#
# Setup
#
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Update packages
      run: apt-get update && apt-get upgrade -y
    - name: Check clang version
      run: clang --version
    - name: Export CLANG compiler flags
      run: |
        export CC=clang
        export CXX=clang++
        export MPICC={OMPI_INSTALL_PATH}/bin/mpiccc
        export MPICXX={OMPI_INSTALL_PATH}/bin/mpicxx
        echo CC="$CC" >> $GITHUB_ENV
        echo CXX="$CXX" >> $GITHUB_ENV
        echo MPICC="$MPICC" >> $GITHUB_ENV
        echo MPICXX="$MPICXX" >> $GITHUB_ENV
        echo "${OMPI_INSTALL_PATH}/bin" >> $GITHUB_PATH
    - name: Show MPI version
      run: mpicc --version
      # This seems to be necessary because of the docker container
    - name: disable ownership checks
      run: git config --global --add safe.directory '*'
    - name: init submodules
      run: git submodule init
    - name: update submodules
      run: git submodule update
    - name: Get input vars
      run: export MAKEFLAGS="${{ inputs.MAKEFLAGS }}"
        && export MPI="${{ inputs.MPI }}"
        && export BUILD_TYPE="${{ inputs.BUILD_TYPE }}"
        && echo MAKEFLAGS="$MAKEFLAGS" >> $GITHUB_ENV
        && echo MPI="$MPI" >> $GITHUB_ENV
        && echo BUILD_TYPE="$BUILD_TYPE" >> $GITHUB_ENV
#
#  T8CODE
# -------
    # build config vars
    - name: Set test level
      run: export TEST_LEVEL_FLAG="-DT8CODE_TEST_LEVEL=${{ inputs.TEST_LEVEL }}"
           && echo TEST_LEVEL_FLAG="$TEST_LEVEL_FLAG" >> $GITHUB_ENV
    - name: build config variables
      run: export CONFIG_OPTIONS="-DCMAKE_C_COMPILER=${OMPI_INSTALL_PATH}/bin/mpicc -DCMAKE_CXX_COMPILER=${OMPI_INSTALL_PATH}/bin/mpicxx ${TEST_LEVEL_FLAG} -GNinja -DCMAKE_C_FLAGS_DEBUG=${DEBUG_CONFIG} -DCMAKE_CXX_FLAGS_DEBUG=${DEBUG_CONFIG} -DT8CODE_BUILD_PEDANTIC=ON -DT8CODE_BUILD_WALL=ON -DT8CODE_BUILD_WERROR=OFF -DT8CODE_BUILD_WEXTRA=ON -DT8CODE_ENABLE_MPI=$MPI -DCMAKE_BUILD_TYPE=$BUILD_TYPE"
        && echo CONFIG_OPTIONS="$CONFIG_OPTIONS" >> $GITHUB_ENV
    # cmake and test
    - name: Printing MPI compiler info
      run: mpicc --version && mpirun --version
    - name: echo cmake line
      run: echo cmake ../ $CONFIG_OPTIONS
    - name: cmake
      run: mkdir build && cd build && cmake ../ $CONFIG_OPTIONS
    - name: OnFailUploadLog
      if: failure()
      uses: actions/upload-artifact@v5
      with:
        name: cmake_w_clang_compiler_${{ inputs.BUILD_TYPE }}_MPI_${{ inputs.MPI }}.log
        path: build/CMakeFiles/CMakeOutput.log
    - name: ninja
      run: cd build && ninja $MAKEFLAGS
    - name: ninja install
      run: cd build && ninja install $MAKEFLAGS
    - name: serial tests (if MPI is enabled)
      run: cd build && ctest $MAKEFLAGS -R _serial
#       if: ${{ inputs.MPI == 'ON' }}
    - name: parallel tests (if MPI is enabled)
      run: cd build && ctest -R _parallel
      env:
        OMPI_ALLOW_RUN_AS_ROOT: 1
        OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
        OMPI_MCA_rmaps_base_oversubscribe: 1
        OMPI_MCA_btl: self,tcp
        OMPI_MCA_pml: ob1
      if: ${{ inputs.MPI == 'ON' }}
    - name: tests (if MPI is disabled)
      run: cd build && ctest $MAKEFLAGS
      if: ${{ inputs.MPI == 'OFF' }}
    - name: OnFailUploadLog
      if: failure()
      uses: actions/upload-artifact@v5
      with:
        name: test-suite_w_clang_compiler_${{ inputs.BUILD_TYPE }}_MPI_${{ inputs.MPI }}.log
        path: build/Testing/Temporary/LastTest.log
