name: t8code cmake tests linkage parallel debug


#  This file is part of t8code.
#  t8code is a C library to manage a collection (a forest) of multiple
#  connected adaptive space-trees of general element types in parallel.
#
#  Copyright (C) 2024 the developers
#
#  t8code is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  t8code is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with t8code; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

#
# This github CI script installs t8code and runs its tests for various configurations.
# We compile sc and p4est as thirdparty libraries and use caching to only trigger a
# new installation of them when their versions have changed in t8code.
#
# Note: To manually enforce sc and p4est installation, either increase the counter
#       in the "key:" entries of the sc and p4est steps or set the variables
#       SC_IGNORE_CACHE and P4EST_IGNORE_CACHE to 1 in the respective steps.

env:
  MAKEFLAGS: "-j2"

on:
  push:
    branches:
      - main
      - develop
      - feature-*CI* # for testing this script, all feature branches with "CI" in their name
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch: # Be able to trigger this manually on github.com
  # Run every night at 1:10
  schedule:
      - cron:  '10 1 * * *'

jobs:
  build:

    if: (github.event_name == 'schedule' && github.repository == 'DLR-AMR/t8code') || (github.event_name != 'schedule')
    runs-on: ubuntu-20.04
    container: dlramr/t8code-ubuntu:t8-dependencies
    timeout-minutes: 90
    steps:
#
# Setup and bootstrap
#
    - uses: actions/checkout@v4
      with: 
        fetch-depth: 0
    - name: Update packages
      run: apt-get update && apt-get upgrade -y
      # This seems to be necessary because of the docker container
    - name: disable ownership checks
      run: git config --global --add safe.directory '*'
    - name: init submodules
      run: git submodule init
    - name: update submodules
      run: git submodule update
#
#       SC installation
#
    - name: store sc folders in var
      run: echo SC_DEBUG=$PWD/sc/build_debug >> $GITHUB_ENV
       && echo SC_RELEASE=$PWD/sc/build_release >> $GITHUB_ENV
    - name: Get sc commit hash
      run: hash=`git rev-parse HEAD:sc` && echo sc_commit=$hash >> $GITHUB_ENV
    - name: Check cache for previous sc installation
      id: sc_cmake_cache
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.SC_DEBUG }}
          ${{ env.SC_RELEASE }}
        # You can increase the counter at the end to force a new key and hence recomputing the cache
        key: sc-cmake-${{ env.sc_commit }}-005
    - name: Set ignore cache variable
      # If this variable is set 1
      # (i.e. SC_IGNORE_CACHE=1) then the cache will be ignored and
      # sc is always build.
      # We use this mostly for debugging this CI script.
      run: echo SC_IGNORE_CACHE=0 >> $GITHUB_ENV
    - name: Cache info
      if: ${{ steps.sc_cmake_cache.outputs.cache-hit != 'true' ||  env.SC_IGNORE_CACHE == 1 }}
      run: echo No cache found or cache will be ignored. SC_IGNORE_CACHE=$SC_IGNORE_CACHE
    - name: if ignore cache, delete folders
      if: ${{ steps.sc_cmake_cache.outputs.cache-hit != 'true' ||  env.SC_IGNORE_CACHE == 1 }}
      # The true at the end is to ignore errors that i.e. occur when the folders do not exist
      run: rm -r $SC_DEBUG || true
    - name: make folders
      run: mkdir $SC_DEBUG
      if: ${{ steps.sc_cmake_cache.outputs.cache-hit != 'true' || env.SC_IGNORE_CACHE == 1 }}
    - name: install sc
      run: echo "Install sc"
      if: ${{ steps.sc_cmake_cache.outputs.cache-hit != 'true' || env.SC_IGNORE_CACHE == 1 }}
      ## sc debug
    - name: sc cmake debug
      run: cd $SC_DEBUG && cmake ../ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$PWD/install -Dmpi=ON
      if: ${{ steps.sc_cmake_cache.outputs.cache-hit != 'true' || env.SC_IGNORE_CACHE == 1 }}
    - name: sc build debug
      run: cd $SC_DEBUG && make $MAKEFLAGS && make $MAKEFLAGS install
      if: ${{ steps.sc_cmake_cache.outputs.cache-hit != 'true' || env.SC_IGNORE_CACHE == 1 }}

#
# P4EST
#
    - name: store p4est folders in var
      run: echo P4EST_DEBUG=$PWD/p4est/build_debug >> $GITHUB_ENV
       && echo P4EST_RELEASE=$PWD/p4est/build_release >> $GITHUB_ENV
    - name: Get p4est commit hash
      run: hash=`git rev-parse HEAD:p4est` && echo p4est_commit=$hash >> $GITHUB_ENV
    - name: Check cache for previous p4est installation
      id: p4est_cmake_cache
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.P4EST_DEBUG }}
          ${{ env.P4EST_RELEASE }}
        # You can increase the counter at the end to force a new key and hence recomputing the cache
        key: p4est-cmake-${{ env.p4est_commit }}-${{ env.sc_commit }}-005
    - name: Set ignore cache variable
      # If this variable is set to 1 then the cache is ignored and p4est is installed regardless of cache.
      # (set with i.e. P4EST_IGNORE_CACHE=1)
      # We use this mostly for debugging this CI script.
      run: echo P4EST_IGNORE_CACHE=0 >> $GITHUB_ENV
    - name: Cache info
      if: ${{ steps.p4est_cmake_cache.outputs.cache-hit != 'true' || env.P4EST_IGNORE_CACHE == 1 }}
      run: echo No cache found or cache will be ignored. P4EST_IGNORE_CACHE=$P4EST_IGNORE_CACHE
    - name: install p4est
      run: echo "Install p4est"
      if: ${{ steps.p4est_cmake_cache.outputs.cache-hit != 'true' || env.P4EST_IGNORE_CACHE == 1 }}
    - name: if ignore cache, delete folders
      if: ${{ steps.p4est_cmake_cache.outputs.cache-hit != 'true' || env.P4EST_IGNORE_CACHE == 1 }}
      # The true at the end is to ignore errors that i.e. occur when the folders do not exist      
      run: rm -r $P4EST_DEBUG $P4EST_RELEASE || true 
    - name: make folders
      if: ${{ steps.p4est_cmake_cache.outputs.cache-hit != 'true' || env.P4EST_IGNORE_CACHE == 1 }}
      run: mkdir $P4EST_DEBUG $P4EST_RELEASE
    ## p4est debug
    - name: p4est cmake debug
      run: cd $P4EST_DEBUG && cmake ../ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$PWD/install -DP4EST_USE_SYSTEM_SC=ON -DSC_DIR=$SC_DEBUG/install/cmake
      if: ${{ steps.p4est_cmake_cache.outputs.cache-hit != 'true' || env.P4EST_IGNORE_CACHE == 1 }}
    - name: p4est build debug
      run: cd $P4EST_DEBUG && make $MAKEFLAGS && make $MAKEFLAGS install
      if: ${{ steps.p4est_cmake_cache.outputs.cache-hit != 'true' || env.P4EST_IGNORE_CACHE == 1 }}
    ## p4est release
    - name: p4est cmake release
      run: cd $P4EST_RELEASE && cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PWD/install -DP4EST_USE_SYSTEM_SC=ON -DSC_DIR=$SC_DEBUG/install/cmake
      if: ${{ steps.p4est_cmake_cache.outputs.cache-hit != 'true' || env.P4EST_IGNORE_CACHE == 1 }}
    - name: p4est build release
      run: cd $P4EST_RELEASE && make $MAKEFLAGS && make $MAKEFLAGS install
      if: ${{ steps.p4est_cmake_cache.outputs.cache-hit != 'true' || env.P4EST_IGNORE_CACHE == 1 }}
#  P4EST AND SC END
#
#  T8CODE
#
#
    # build config vars
    - name: less-test-option
      if: github.event_name == 'pull_request'
      run: export LESS_TEST_OPTION="--enable-less-tests"
           && echo LESS_TEST_OPTION="$LESS_TEST_OPTION" >> $GITHUB_ENV
    - name: build config variables
      #TODO: Werror
      run: export CONFIG_OPTIONS="${LESS_TEST_OPTION} -DT8CODE_USE_SYSTEM_SC=ON -DT8CODE_USE_SYSTEM_P4EST=ON"
           && export CONFIG_DEBUG="$CONFIG_OPTIONS -DCMAKE_BUILD_TYPE=Debug -DSC_DIR=$SC_DEBUG/install/cmake -DP4EST_DIR=$P4EST_DEBUG/install/cmake"
           && echo CONFIG_OPTIONS="$CONFIG_OPTIONS" >> $GITHUB_ENV
           && echo CONFIG_DEBUG="$CONFIG_DEBUG" >> $GITHUB_ENV
    - name: Check vars
      run: echo "[$CONFIG_DEBUG]"
# cmake and test with MPI and netcdf (debug mode)
#    - name: check NetCDF
#      run: echo "Checking NetCDF with MPI in debugging mode"
#    - name: cmake MPI NetCDF debug
#      run: mkdir build_netcdf && cd build_netcdf && cmake ../ $CONFIG_DEBUG -DT8CODE_ENABLE_OCC=ON
#    - name: OnFailUploadLog
#      if: failure()
#      uses: actions/upload-artifact@v4
#      with:
#        name: cmake_netcdf_debug_MPI.log
#        path: build_netcdf/CMakeFiles/CMakeOutput.log
#    - name: make
#      run: cd build_netcdf && make $MAKEFLAGS
#    - name: make install
#      run: cd build_netcdf && make install $MAKEFLAGS
#    - name: make test
#      run: cd build_netcdf && make test $MAKEFLAGS
#    - name: OnFailUploadLog
#      if: failure()
#      uses: actions/upload-artifact@v4
#      with:
#        name: test-suite_netcdf.log
#        path: build_netcdf/test-suite.log
# cmake and test with MPI and OpenCASCADE (debug mode)
    - name: check OpenCASCADE
      run: echo "Checking OpenCASCADE with MPI in debugging mode"
    - name: cmake MPI OpenCASCADE debug
      run: mkdir build_cad && cd build_cad && cmake ../ $CONFIG_DEBUG -DT8CODE_ENABLE_OCC -DOpenCASCADE_DIR="/usr/include/opencascade"
    - name: OnFailUploadLog
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: cmake_cad_debug_MPI.log
        path: build_cad/CMakeFiles/CMakeOutput.log
    - name: make
      run: cd build_cad && make $MAKEFLAGS
    - name: make install
      run: cd build_cad && make install $MAKEFLAGS
    - name: make test
      run: cd build_cad && make test $MAKEFLAGS
    - name: OnFailUploadLog
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-suite_cad.log
        path: build_cad/test-suite.log
# cmake and test with MPI and VTK (debug mode)
    - name: check VTK
      run: echo "Checking VTK with MPI in debugging mode"
    - name: cmake MPI VTK debug
      run: mkdir build_vtk && cd build_vtk && cmake ../ $CONFIG_DEBUG -DT8CODE_ENABLE_VTK -DVTK_DIR="/usr/local/include/vtk-9.1"
    - name: OnFailUploadLog
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: cmake_vtk_debug_MPI.log
        path: build_vtk/CMakeFiles/CMakeOutput.log
    - name: make
      run: cd build_vtk && make $MAKEFLAGS
    - name: make install
      run: cd build_vtk && make install $MAKEFLAGS
    - name: make test
      run: cd build_vtk && make test $MAKEFLAGS
    - name: OnFailUploadLog
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-suite_vtk.log
        path: build_vtk/test-suite.log
